#
# Sera - OnePage Jekyll Template
# Configuration File
#
#

markdown: kramdown
markdown_ext: "markdown,mkdown,md,mkd,mkdn"

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README-sera.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Indigo Beetle
# Website language
lang: en-GB
# Header Title
header-title: <strong>Left Brain</strong> <em>Right Brain</em>
# Header Tagline
headter-tagline: Uncomplicating the complicated

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
#header-focus-button:
#  title: Download Now
#  url: https://themeforest.net/collections/6069390-sera

# Secondary Buttons
#header-secondary-button:
#  title: Discover More
#  url: http://themeforest.net/user/gleesik

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: pgregory@indigobeetle.co.uk

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
#youtube: '#'
#pinterest: '#'
facebook: 'https://www.facebook.com/indigobeetle/'
#twitter: 'https://twitter.com/pcgregory'
#google-plus: '#'
#vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar.jpg
  author-name: Paul Gregory
  author-tagline: Software Guru
  author-info: Driven by the desire to empower the worlds' Right Brains through technology.
  author-social-links:
    #youtube: '#'
    #pinterest: '#'
    facebook: 'https://www.facebook.com/pcgregory'
    twitter: 'https://twitter.com/pcgregory'
    #google-plus: '#'

# Google Map JS api
# This is my api for this template
#key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
#map-text: Sera Google Map
#map-text-location: Bucharest, Romania
#map-lat: 44.4267674
#map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: 55a3ba457c48738318dd70dfb
  list-id: eb4745d6d0
  list-action: 'https://indigobeetle.us16.list-manage.com/subscribe/post'

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesikâ„¢
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: A Little About Me
about-description: |+
  Hi, I'm Paul, a self confessed nerd and part time geek.
  <br /><br />
  My overriding goal in life is to create hi-tech tools for non-hi-tech people. 
  I thrive on building software that unlocks the creative potential of others, 
  and am always on the lookout for the next big thing that brings technology to
  a new audience in a way that hasn't been achieved before.
  <br /><br />
  I enjoy everything to do with creative media and entertainement, from games to 
  films and everything in-between. Working with creative teams most of my career
  gives me an insight into the ways of working and enables me to understand the 
  needs of the creative individual, digging under the superficial request to find
  unique and innovative solutions.
  <br /><br />
  I apply 30 years of experience in the software industry, working with some of
  the most talented people in the field, to design, plan and implement with an
  extremely high level of rigour and quality.

#####################################
#############  Expertise  ############
#####################################
features-title: Expertise
features-description: I can apply my software engineering experience to almost any software problem, but here are some examples of my specialisations.

#
# Features
#
features:

# Feature
- title: Digital Audio
  description: Building the future of collaborative music, right here on the web. Bringing musicians together in a digital age.
  icon: pe-7s-music

# Feature
- title: Video Games 
  description: From retro to next-gen, casual to hardcore; applying years of experience, from 8bit home computers to mobiles, to allow games designers to realise their dreams. 
  icon: pe-7s-joy

# Feature
- title: CGI & Visual Effects
  description: Photo-realistic rendering, animation, procedural systems, generative systems, advanced physical simulation. 
  icon: pe-7s-film


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Some of the projects and products I've worked on, professionally or as hobby/side projects.

#
# Portfolio Grid
#
portfolio-categories: [Websites, Digital Audio, Games, Development, Web Applications]
portfolio:

# Portfolio Item
- title: WeTracker
  categories: [Digital Audio, Web Applications]
  image: wetracker1.png
  thumb: wetracker1-thumb.png
  url: 'http://app.wetracker.xyz'

# Portfolio Item
- title: Pico8 Shooter
  categories: [Games]
  image: pico8-shooter.png
  thumb: pico8-shooter-thumb.png
  url: '/portfolio/shmup/shmup.html'

# Portfolio Item
- title: Pendng.com
  categories: [Web Applications]
  image: pendng.png
  thumb: pendng-thumb.png
  url: 'https://app.pendng.com'
  
# Portfolio Item
- title: Fruit Spritzer 
  categories: [Games]
  image: fruit.png
  thumb: fruit-thumb.png
  url: 'https://apps.facebook.com/fruitspritzer'

# Portfolio Item
- title: Tracker Radio 
  categories: [Web Applications, Websites]
  image: tracker-radio.png
  thumb: tracker-radio-thumb.png
  url: 'https://indigobeetle.pythonanywhere.com'

# Portfolio Item
- title: Cact-Eye
  categories: [Games]
  image: cact-eye.png
  thumb: cact-eye-thumb.png
  url: 'https://indigobeetle.itch.io/cact-eye'

# Portfolio Item
- title: Children's Games 
  categories: [Games]
  image: mardyboys.png
  thumb: mardyboys-thumb.png
  url: 'http://www.games.mardyboys.com/'

#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: A few words from some of the people I've been fortunate enough to work alongside through my career.

#
# Testimonials
#
testimonials:

# Client
- name: Michael Steliaros
  avatar: steliaros.jpg
  url: https://www.linkedin.com/in/michaelsteliaros/
  url-text: Director of Research, Glu Mobile
  cite: | 
    Paul is highly results focused and consistent at getting outstanding results in the face of competing priorities. Always keeps the greater picture in mind and is highly objective.<br />
    Self-motivated and always willing to take independent action, comes up with great ideas and solid implementation based on considered research & design.<br />
    One of the most dependable people on the team and can always be counted upon to deliver. Can be trusted with important decisions and he has the skill to get things done.
  logo-img: glu_logo.png

# Client
- name: Zahir Mazhar
  url: https://www.linkedin.com/in/zahir-mazhar-0541099/
  url-text: Technical Lead Project Manager, Red Dot Square Solutions Ltd.
  avatar: zahir.jpg
  cite: Paul is a self motivated and supportive leader who not only listens but also coaches and mentors his teams to perform to their best. With excellent knowledge of all things technical, Paul can be relied upon to provide innovative and creative solutions to complex issues, which, will meet and exceed quality and customer expectations. As my Line manager, Paul was a true mentor and coach who gains the respect of his teams by being hands on and involved in resolving issues.
  logo-img: rdss.gif

# Client
- name: Jonathan Privett
  url: https://www.linkedin.com/in/jonathan-privett-0353941/
  url-text: Head of Film & TV, Rushes Postproduction
  avatar: jonathan.jpg
  cite: Paul was an incredible asset to the team here at Rushes and his technical knowledge in the sphere of 3D rendering is immense. He also managed to learn the relevant software and write from scratch a shot tracking program showcasing his ability to change discipline and program pretty much anything. It was certainly a loss when Paul moved on and I'd recommend him to anyone seeking a resourceful and highly knowledgeable software architect.
  logo-img: rushes-postproduction.png

# Client
- name: Bryan Salt
  url: https://www.linkedin.com/in/bryan-salt-7869ab17/
  url-text: Global Creative Director, Superscape Ltd.
  avatar: bryan.jpg
  cite: I was lucky enough to work with Paul for many years including my first job at incentive software, a company that produced ground breaking 3d games on low powered machines in the 80s. Paul was one of three cutting edge engineers that were some of the best I have worked with in my long career. What made Paul stand out was his ability to listen to the users, designers and other non programers, understand the business need and incorporate these needs into his design for the tools. 24 years later, Paul is still the guy I drop a call to if I have an impossible problem that no one else can help with, he is always happy to help out and point me in the right direction. I recommend Paul as a highly talented, open minded, flexible, experienced and thoroughly nice chap.
  logo-img: superscape_logo.jpg

# Client
- name: Gavin Simpson 
  url: https://www.linkedin.com/in/gavinssimpson/
  url-text: GPU Compute Engineer, ARM Holdings
  avatar: gavhead.jpg
  cite: |+
    Paul is an outstanding engineer. I've worked with him over many years and can vouch that his software engineering skills are second to none. Complex mathematical problems (think 3D renderer) or more creative development skills, not a problem. He also has the knack of explaining tricky concepts in easy to understand terms which proves very reassuring.  
    <br /><br />
    In short, if you're looking for flawless advice, and a solid well engineered solution implemented impossibly quickly, seek out Paul.
  logo-img: arm_logo.png

- name: Ian Gregory 
  avatar: steliaros.jpg
  url: https://www.linkedin.com/in/michaelsteliaros/
  url-text: Sky Engineer; Sky TV 
  cite: | 
          Paul is the best brother in the world!
  logo-img: glu_logo.png

#####################################
############# Blog ##############
#####################################
blog-title: Blog
blog-description: 


#####################################
############   Contact   ############
#####################################
contact-title: Contact Me
contact-description: 


#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: Indigo Beetle&trade;
footer-copyright-url: https://www.indigobeetle.co.uk
footer-copyright-year: 2017

gems:
  - jekyll-sitemap
